#pragma once
/* Main Loop */
enum OPMODE
{
	OP_MODE_RECV = 0,
	OP_MODE_SEND,
	OP_MODE_ACCEPT,
	OP_ACTIVE_NPC,
	OP_MODE_CHASE_MONSTER,
	OP_MODE_REGEN_MONSTER,
	OP_MODE_BOSS_NEXT_ATTACK,
	OP_MODE_ACTIVE_AI,
	OP_MODE_CHASE_AI,
	OP_MODE_AI_NEXT_ATTACK,
	OP_MODE_END
};

/* OBJECT STATUS */
enum STATUS { ST_ACTIVE = 0, ST_NONACTIVE, ST_CHASE, ST_ATTACK, ST_REACTION, ST_DEAD, ST_END };

/* Item Type */
//enum ITEM { ITEM_WEAPON, ITEM_ARMOR, ITEM_ETC, ITEM_END };
enum ITEM {
	ITEM_WEAPON_SWORD, ITEM_WEAPON_BOW, ITEM_WEAPON_ROD,
	ITEM_HELMET, ITEM_ARMOR, ITEM_SHOES, 
	ITEM_ETC,
	ITEM_END
};